# Generated by Django 2.2.18 on 2021-04-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('descriptor_ui', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('descriptor_name', models.CharField(max_length=128)),
                ('label', models.TextField(max_length=128)),
                ('parents', models.ManyToManyField(related_name='children', to='rdmo_mesh.Descriptor')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('qualifier_ui', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('qualifier_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TreeNumber',
            fields=[
                ('tree_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_list', to='rdmo_mesh.Descriptor')),
            ],
        ),
        migrations.AddField(
            model_name='descriptor',
            name='qualifiers',
            field=models.ManyToManyField(related_name='descriptors', to='rdmo_mesh.Qualifier'),
        ),
    ]
