# Generated by Django 2.2.24 on 2021-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdmo_mesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_ui', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('string', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_ui', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('concept_name', models.CharField(max_length=256)),
                ('terms', models.ManyToManyField(related_name='concepts', to='rdmo_mesh.Term')),
            ],
        ),
        migrations.AddField(
            model_name='descriptor',
            name='concepts',
            field=models.ManyToManyField(related_name='descriptors', to='rdmo_mesh.Concept'),
        ),
    ]
