# Generated by Django 2.2.24 on 2021-07-26 09:21

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdmo_mesh', '0002_add_concept_and_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
