# Generated by Django 2.2.24 on 2021-07-26 09:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdmo_mesh', '0003_descriptor_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='descriptor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='rdmo_mesh_d_search__ab28c3_gin'),
        ),
    ]
